kind: pipeline

name: default
type: docker

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      command_timeout: 30m
      script:
        - ls -l
    when:
      branch:
        - clean-server
      status:
        - success
