version: "3.9"
services:
  infinityedge:
    build: .
    image: node:bullseye
    environment:
      - FTP_URL=${FTP_URL}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
    volumes:
      - ./events:/infinityedge/events
